---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Stop services
  systemd:
    name: "{{ item.service_name }}"
    enabled: yes
    state: "stopped"
    daemon_reload: yes
  with_items: "{{ filtered_zun_services }}"
  register: _stop
  until: _stop | success
  retries: 5
  delay: 2
  listen: "Restart zun services"

- name: Start services
  systemd:
    name: "{{ item.service_name }}"
    enabled: yes
    state: "started"
    daemon_reload: yes
  with_items: "{{ filtered_zun_services }}"
  register: _start
  until: _start | success
  retries: 5
  delay: 2
  listen: "Restart zun services"

- name: Stop docker
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "stopped"
    daemon_reload: yes
  with_items:
    - docker
    - kuryr-libnetwork
  register: _stop
  until: _stop | success
  retries: 5
  delay: 2
  listen: "Restart kuryr services"

- name: Start docker
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "started"
    daemon_reload: yes
  with_items:
    - docker
    - kuryr-libnetwork
  register: _start
  until: _start | success
  retries: 5
  delay: 2
  listen: "Restart kuryr services"

- meta: noop
  listen: Manage LB
  when: false
